import { test } from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const source = fs.readFileSync(new URL('../integration/Code.gs', import.meta.url), 'utf8');
test('Google adapter maps all answers, prevents duplicate rows and rejects unauthorized or invalid submissions', () => {
 const rows=[];const token='test-only-token-at-least-24-characters';let headers;const cache=new Map();
 const sheet={getRange:(row,col)=>({getValues:()=>[headers],createTextFinder:id=>({matchEntireCell:()=>({findNext:()=>rows.some(r=>r[17]===id)?{}:null})})}),getLastRow:()=>rows.length+1,appendRow:row=>rows.push(row)};
 const context=vm.createContext({CacheService:{getScriptCache:()=>({get:key=>cache.get(key),put:(key,value)=>cache.set(key,value)})},PropertiesService:{getScriptProperties:()=>({getProperty:()=>token})},LockService:{getScriptLock:()=>({waitLock(){},hasLock:()=>true,releaseLock(){}})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet}),flush(){}},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({setMimeType:()=>JSON.parse(text)})}});
 vm.runInContext(source,context);headers=vm.runInContext('HEADERS',context);
 const lead={token,name:'=FORMULA()',phone:'9000000000',fillingFor:'Friend',gender:'Female',city:'Salem',concern:'Hernia',surgeryAdvised:'Not Sure',duration:'More than 1 year',comfortable:'No',consent:true,requestId:'11111111-1111-4111-8111-111111111111',campaign:{utm_source:'google'}};
 const send=data=>context.doPost({postData:{contents:JSON.stringify(data)}});
 assert.equal(send({...lead,token:'wrong'}).ok,false);assert.equal(send({...lead,city:'Invalid'}).ok,false);assert.equal(rows.length,0);
 assert.equal(send(lead).ok,true);assert.equal(rows.length,1);assert.equal(rows[0].length,19);assert.equal(rows[0][1],"'=FORMULA()");assert.equal(rows[0][2],'Friend');assert.equal(rows[0][3],"'9000000000");assert.equal(rows[0][4],'Female');assert.equal(rows[0][5],'Salem');assert.equal(rows[0][6],'Hernia');assert.equal(rows[0][7],'Not Sure');assert.equal(rows[0][8],'More than 1 year');assert.equal(rows[0][9],'No');assert.equal(rows[0][10],'Yes');assert.equal(rows[0][11],'google');assert.equal(rows[0][17],lead.requestId);assert.equal(rows[0][18],'New');
 assert.equal(send(lead).ok,true);assert.equal(rows.length,1);
 assert.deepEqual(send({action:'status'}),{ok:true,publicFormVersion:1});
 assert.equal(rows.length,1,'status never writes a lead');
 const publicLead={...lead,token:undefined,source:'kmch-landing-page',phone:'9000000001',requestId:'22222222-2222-4222-8222-222222222222'};
 for (const invalid of [null,[],{...publicLead,source:''},{...publicLead,website:'spam'},{...publicLead,consent:false},{...publicLead,comfortable:'invalid'},{...publicLead,name:'x'.repeat(9000)}]) assert.equal(send(invalid).ok,false);
 assert.equal(send(publicLead).ok,true);
 assert.equal(send(publicLead).ok,true);
 assert.equal(rows.length,2,'public retries do not create duplicates');
 for (const suffix of ['3','4']) assert.equal(send({...publicLead,requestId:suffix.repeat(32)}).ok,true);
 assert.equal(send({...publicLead,requestId:'5'.repeat(32)}).ok,false,'limit repeated requests for one phone');
 assert.equal(rows.length,4);
 assert.equal(send(publicLead).ok,true,'a successful retry still works at the limit');
 headers=['wrong'];assert.equal(send({action:'status'}).ok,false,'bad sheet configuration keeps the form disabled');
});
